Add friends likes
kapetrosyan1/java-filmorate pull request #15
Opened 2023-11-20 23:24 UTC by kapetrosyan1

2023-11-21 13:49 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Autowired
На единственном конструкторе не обязательно ставить эту аннотацию, по умолчанию Спринг внедряет зависимости в единственный конструктор

2023-11-21 18:12 UTC, kapetrosyan1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Autowired
Понял. Уберу аннотации. В остальном все нормально? Можно merge делать?

2023-11-21 21:07 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
Вот эту проверку можно. вынести отдельным методом, так как она повторяется ниже

2023-11-21 21:07 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getName() == null || film.getName().isBlank()) {
вынеси маленькие методы из этого большого, так будет выглядеть проще и понятнее

2023-11-21 21:09 UTC, PolnySkvorets requested changes
Привет! Оставил несколько мелких замечаний на поправить

2023-11-21 21:09 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Не обязательно на единственный конструктор вешать эту аннотацию, спринг по умолчанию внедрит зависимости в единственный конструктор

2023-11-23 08:14 UTC, PolnySkvorets approved these changes
привет! Всё отлично исправил

2023-11-24 15:45 UTC, merged